/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.CategorieDAO;
import DAO.LieuDAO;
import DAO.MarqueDAO;
import DAO.SingletonConnexion;
import DAO.VehiculeDAO;
import JavaBeans.Categorie;
import JavaBeans.Lieu;
import JavaBeans.Marque;
import JavaBeans.Vehicule;
import Utiles.DateGetter;
import Utiles.VehiculeTableModel;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author Moustaid
 */
public class IHMAddVehicule extends javax.swing.JFrame {
private DateGetter dateGetter=new DateGetter();
private VehiculeDAO vDAO=new VehiculeDAO(SingletonConnexion.getInstance());

    /**
     * Creates new form Accueil
     */
    public IHMAddVehicule() {
        initComponents();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerPanel = new javax.swing.JPanel();
        panelCenter = new javax.swing.JPanel();
        labName = new javax.swing.JLabel();
        labDate = new javax.swing.JLabel();
        panelRecherche = new javax.swing.JPanel();
        labRechercherPar = new javax.swing.JLabel();
        panelBtn = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnAccueil = new javax.swing.JButton();
        panelTable = new javax.swing.JPanel();
        labMatricule = new javax.swing.JLabel();
        labCategorie = new javax.swing.JLabel();
        comboCategorie = new javax.swing.JComboBox();
        labMarque = new javax.swing.JLabel();
        comboMarque = new javax.swing.JComboBox();
        labKM = new javax.swing.JLabel();
        txtKM = new javax.swing.JSpinner();
        labLieu = new javax.swing.JLabel();
        comboLieu = new javax.swing.JComboBox();
        labcouleur = new javax.swing.JLabel();
        comboCouleur = new javax.swing.JComboBox();
        labDateAjout = new javax.swing.JLabel();
        txtDate = new javax.swing.JFormattedTextField();
        labDateForme = new javax.swing.JLabel();
        labMatriculeForm = new javax.swing.JLabel();
        txtMatricule = new javax.swing.JFormattedTextField();
        labMax1 = new javax.swing.JLabel();
        labBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Véhicules OCP - Ajout de véhicule");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        containerPanel.setBackground(new java.awt.Color(255, 102, 102));
        containerPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        containerPanel.setLayout(new java.awt.BorderLayout());

        panelCenter.setBackground(new java.awt.Color(255, 255, 0));
        panelCenter.setOpaque(false);
        panelCenter.setPreferredSize(new java.awt.Dimension(800, 500));
        panelCenter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        labName.setForeground(new java.awt.Color(53, 83, 65));
        labName.setPreferredSize(new java.awt.Dimension(34, 20));
        panelCenter.add(labName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 25, 280, 33));

        labDate.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        labDate.setForeground(new java.awt.Color(53, 83, 65));
        labDate.setPreferredSize(new java.awt.Dimension(220, 33));
        panelCenter.add(labDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 25, -1, -1));

        panelRecherche.setOpaque(false);

        labRechercherPar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        labRechercherPar.setText("Ajout de Véhicule");
        panelRecherche.add(labRechercherPar);

        panelCenter.add(panelRecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 100, 560, 50));

        panelBtn.setOpaque(false);

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnAdd.png"))); // NOI18N
        btnAdd.setToolTipText("Ajouter");
        btnAdd.setBorderPainted(false);
        btnAdd.setContentAreaFilled(false);
        btnAdd.setFocusPainted(false);
        btnAdd.setPreferredSize(new java.awt.Dimension(106, 102));
        btnAdd.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddMouseExited(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        panelBtn.add(btnAdd);

        btnAccueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnAccueil.png"))); // NOI18N
        btnAccueil.setToolTipText("Retour");
        btnAccueil.setBorderPainted(false);
        btnAccueil.setContentAreaFilled(false);
        btnAccueil.setFocusPainted(false);
        btnAccueil.setPreferredSize(new java.awt.Dimension(106, 102));
        btnAccueil.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAccueil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAccueil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAccueilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAccueilMouseExited(evt);
            }
        });
        btnAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccueilActionPerformed(evt);
            }
        });
        panelBtn.add(btnAccueil);

        panelCenter.add(panelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 560, 100));

        panelTable.setOpaque(false);
        panelTable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labMatricule.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labMatricule.setText("Matricule :");
        labMatricule.setPreferredSize(new java.awt.Dimension(130, 30));
        panelTable.add(labMatricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 100, 30));

        labCategorie.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labCategorie.setText("Categorie :");
        labCategorie.setPreferredSize(new java.awt.Dimension(130, 30));
        panelTable.add(labCategorie, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 45, 100, 30));

        comboCategorie.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboCategorie.setOpaque(false);
        comboCategorie.setPreferredSize(new java.awt.Dimension(130, 30));
        panelTable.add(comboCategorie, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 45, 170, 30));

        labMarque.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labMarque.setText("Marque :");
        labMarque.setPreferredSize(new java.awt.Dimension(130, 30));
        panelTable.add(labMarque, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 100, 30));

        comboMarque.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboMarque.setOpaque(false);
        comboMarque.setPreferredSize(new java.awt.Dimension(130, 30));
        panelTable.add(comboMarque, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 170, 30));

        labKM.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labKM.setText("Kilométrage :");
        labKM.setPreferredSize(new java.awt.Dimension(130, 30));
        panelTable.add(labKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 115, 100, 30));

        txtKM.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtKM.setModel(new javax.swing.SpinnerNumberModel(0, 0, 800000, 1));
        txtKM.setOpaque(false);
        txtKM.setPreferredSize(new java.awt.Dimension(130, 30));
        panelTable.add(txtKM, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 115, 170, 30));

        labLieu.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labLieu.setText("Lieu :");
        labLieu.setPreferredSize(new java.awt.Dimension(130, 30));
        panelTable.add(labLieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 100, 30));

        comboLieu.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboLieu.setOpaque(false);
        comboLieu.setPreferredSize(new java.awt.Dimension(130, 30));
        comboLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboLieuActionPerformed(evt);
            }
        });
        panelTable.add(comboLieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 170, 30));

        labcouleur.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labcouleur.setText("Couleur :");
        labcouleur.setPreferredSize(new java.awt.Dimension(130, 30));
        panelTable.add(labcouleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 185, 100, 30));

        comboCouleur.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        comboCouleur.setOpaque(false);
        comboCouleur.setPreferredSize(new java.awt.Dimension(130, 30));
        panelTable.add(comboCouleur, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 185, 170, 30));

        labDateAjout.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labDateAjout.setText("Date Ajout :");
        panelTable.add(labDateAjout, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 100, 30));

        txtDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        panelTable.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 170, 30));

        labDateForme.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labDateForme.setText("(YYYY-MM-DD)");
        panelTable.add(labDateForme, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, 30));

        labMatriculeForm.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labMatriculeForm.setText("(#####/*/##)");
        panelTable.add(labMatriculeForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 110, 30));

        try {
            txtMatricule.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####/*/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtMatricule.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtMatricule.setPreferredSize(new java.awt.Dimension(170, 30));
        panelTable.add(txtMatricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        labMax1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labMax1.setText("Max : 800 000 km");
        panelTable.add(labMax1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 115, 110, 30));

        panelCenter.add(panelTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 192, 670, 270));

        containerPanel.add(panelCenter, java.awt.BorderLayout.LINE_START);

        labBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg2.png"))); // NOI18N
        containerPanel.add(labBG, java.awt.BorderLayout.LINE_END);

        getContentPane().add(containerPanel, java.awt.BorderLayout.LINE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseEntered
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnAdd2.png"))); // NOI18N
    }//GEN-LAST:event_btnAddMouseEntered

    private void btnAccueilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccueilMouseEntered
        btnAccueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnAccueil2.png"))); // NOI18N
    }//GEN-LAST:event_btnAccueilMouseEntered

    private void btnAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseExited
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnAdd.png"))); // NOI18N
    }//GEN-LAST:event_btnAddMouseExited

    private void btnAccueilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccueilMouseExited
        btnAccueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnAccueil.png"))); // NOI18N
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAccueilMouseExited

    private void btnAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccueilActionPerformed
IHMVehicules ihmVehicules=new IHMVehicules();   
this.dispose();
ihmVehicules.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAccueilActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
labDate.setText(dateGetter.getDayName()+", "+dateGetter.getDateNow());
        labName.setText(IHMLogin.user.getNomUser().toUpperCase()+" "+IHMLogin.user.getPrenomUser());
CategorieDAO cDAO=new CategorieDAO(SingletonConnexion.getInstance());
MarqueDAO mDAO=new MarqueDAO(SingletonConnexion.getInstance());
LieuDAO lDAO=new LieuDAO(SingletonConnexion.getInstance());
List<Categorie> lc=new ArrayList();
List<Marque> lm=new ArrayList();
List<Lieu> ll=new ArrayList();
lc=cDAO.readAll();
lm=mDAO.readAll();
ll=lDAO.readAll();
String validation=null;
if(lc.size()==0)
    validation=validation+",Catégorie";
if(lm.size()==0)
        validation=validation+",Marque";

if(ll.size()==0)
       validation=validation+",Lieu";
if(validation!=null)
{
    JOptionPane.showMessageDialog(this, "Il n'y a aucun(e) "+validation+" Lieu dans votre base de données !");
    btnAdd.setEnabled(false);
}else{
for(Categorie c:lc)
comboCategorie.addItem(c.getIdCategorie()+":"+c.getNomCategorie());
comboCategorie.setSelectedIndex(0);
for(Marque m:lm)
comboMarque.addItem(m.getIdMarque()+":"+m.getNomMarque());
comboMarque.setSelectedIndex(0);
for(Lieu l:ll)
comboLieu.addItem(l.getIdLieu()+":"+l.getNomLieu());
comboLieu.setSelectedIndex(0);
}
txtDate.setText(dateGetter.getDateNow());

comboCouleur.addItem("Noir");
comboCouleur.addItem("Bleu");
comboCouleur.addItem("Gris");
comboCouleur.addItem("Vert");
comboCouleur.addItem("Orange");
comboCouleur.addItem("Rose");
comboCouleur.addItem("Rouge");
comboCouleur.addItem("Blanc");
comboCouleur.addItem("Jaune");
comboCouleur.addItem("Marron");
comboCouleur.setSelectedIndex(0);



// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
Categorie c=new Categorie();
Marque m=new Marque();
Lieu l=new Lieu();
Vehicule v=new Vehicule();
if(vDAO.isMatriculeExiste(txtMatricule.getText()))
JOptionPane.showMessageDialog(this, "le Matricule existe déja !");
else{
    if(String.valueOf(txtMatricule.getValue()).length()<10)
    JOptionPane.showMessageDialog(this, "le Matricule ne suit pas la forme standard !");
    else{
v.setMatricule(txtMatricule.getText());
c.setIdCategorie(Integer.parseInt(String.valueOf(comboCategorie.getSelectedItem()).split(":")[0]));
m.setIdMarque(Integer.parseInt(String.valueOf(comboMarque.getSelectedItem()).split(":")[0]));
l.setIdLieu(Integer.parseInt(String.valueOf(comboLieu.getSelectedItem()).split(":")[0]));
v.setCategorie(c);
v.setMarque(m);
v.setLieu(l);
v.setKilometrage(Integer.parseInt(String.valueOf(txtKM.getValue())));
v.setCouleur(String.valueOf(comboCouleur.getSelectedItem()));
v.setDateAjout(txtDate.getText()); 
System.out.println(txtDate.getText());
vDAO.create(v);
JOptionPane.showMessageDialog(this,"Véhicule Ajouté !" );
IHMVehicules ihmvehicules=new IHMVehicules();
this.dispose();
ihmvehicules.setVisible(true);
    }
}         // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void comboLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboLieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboLieuActionPerformed


     
       


    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccueil;
    private javax.swing.JButton btnAdd;
    private javax.swing.JComboBox comboCategorie;
    private javax.swing.JComboBox comboCouleur;
    private javax.swing.JComboBox comboLieu;
    private javax.swing.JComboBox comboMarque;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JLabel labBG;
    private javax.swing.JLabel labCategorie;
    private javax.swing.JLabel labDate;
    private javax.swing.JLabel labDateAjout;
    private javax.swing.JLabel labDateForme;
    private javax.swing.JLabel labKM;
    private javax.swing.JLabel labLieu;
    private javax.swing.JLabel labMarque;
    private javax.swing.JLabel labMatricule;
    private javax.swing.JLabel labMatriculeForm;
    private javax.swing.JLabel labMax1;
    private javax.swing.JLabel labName;
    private javax.swing.JLabel labRechercherPar;
    private javax.swing.JLabel labcouleur;
    private javax.swing.JPanel panelBtn;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelRecherche;
    private javax.swing.JPanel panelTable;
    private javax.swing.JFormattedTextField txtDate;
    private javax.swing.JSpinner txtKM;
    private javax.swing.JFormattedTextField txtMatricule;
    // End of variables declaration//GEN-END:variables

   
}
