/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Utiles.DateGetter;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JOptionPane;

/**
 *
 * @author Moustaid
 */
public class IHMAccueil extends javax.swing.JFrame {
DateGetter dateGetter=new DateGetter();
    /**
     * Creates new form Accueil
     */
    public IHMAccueil() {
        initComponents();
        labDate.setText(dateGetter.getDayName()+", "+dateGetter.getDateNow());
        labName.setText(IHMLogin.user.getNomUser().toUpperCase()+" "+IHMLogin.user.getPrenomUser());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerPanel = new javax.swing.JPanel();
        panelCenter = new javax.swing.JPanel();
        btnVehicule = new javax.swing.JButton();
        btnCategorie = new javax.swing.JButton();
        btnMarque = new javax.swing.JButton();
        btnLieu = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        btnUtilisateur = new javax.swing.JButton();
        btnApropos = new javax.swing.JButton();
        btnQuitter = new javax.swing.JButton();
        labVehicule = new javax.swing.JLabel();
        labCategorie = new javax.swing.JLabel();
        labMarque = new javax.swing.JLabel();
        labLieu = new javax.swing.JLabel();
        labDivision = new javax.swing.JLabel();
        labUtilisateur = new javax.swing.JLabel();
        labApropos = new javax.swing.JLabel();
        labQuitter = new javax.swing.JLabel();
        labName = new javax.swing.JLabel();
        labDate = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        labBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Véhicules OCP - Accueil");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        containerPanel.setBackground(new java.awt.Color(255, 102, 102));
        containerPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        containerPanel.setLayout(new java.awt.BorderLayout());

        panelCenter.setBackground(new java.awt.Color(255, 255, 0));
        panelCenter.setOpaque(false);
        panelCenter.setPreferredSize(new java.awt.Dimension(800, 500));
        panelCenter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVehicule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnVehicule.png"))); // NOI18N
        btnVehicule.setBorderPainted(false);
        btnVehicule.setContentAreaFilled(false);
        btnVehicule.setFocusPainted(false);
        btnVehicule.setPreferredSize(new java.awt.Dimension(106, 102));
        btnVehicule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnVehiculeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnVehiculeMouseExited(evt);
            }
        });
        btnVehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculeActionPerformed(evt);
            }
        });
        panelCenter.add(btnVehicule, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        btnCategorie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnCategorie.png"))); // NOI18N
        btnCategorie.setBorderPainted(false);
        btnCategorie.setContentAreaFilled(false);
        btnCategorie.setFocusPainted(false);
        btnCategorie.setPreferredSize(new java.awt.Dimension(106, 102));
        btnCategorie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCategorieMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCategorieMouseExited(evt);
            }
        });
        btnCategorie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategorieActionPerformed(evt);
            }
        });
        panelCenter.add(btnCategorie, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        btnMarque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnMarque.png"))); // NOI18N
        btnMarque.setBorderPainted(false);
        btnMarque.setContentAreaFilled(false);
        btnMarque.setFocusPainted(false);
        btnMarque.setPreferredSize(new java.awt.Dimension(106, 102));
        btnMarque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMarqueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMarqueMouseExited(evt);
            }
        });
        btnMarque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarqueActionPerformed(evt);
            }
        });
        panelCenter.add(btnMarque, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, -1, -1));

        btnLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnLieu.png"))); // NOI18N
        btnLieu.setBorderPainted(false);
        btnLieu.setContentAreaFilled(false);
        btnLieu.setFocusPainted(false);
        btnLieu.setPreferredSize(new java.awt.Dimension(106, 102));
        btnLieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLieuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLieuMouseExited(evt);
            }
        });
        btnLieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLieuActionPerformed(evt);
            }
        });
        panelCenter.add(btnLieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        btnDivision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnDivision.png"))); // NOI18N
        btnDivision.setBorderPainted(false);
        btnDivision.setContentAreaFilled(false);
        btnDivision.setFocusPainted(false);
        btnDivision.setPreferredSize(new java.awt.Dimension(106, 102));
        btnDivision.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDivisionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDivisionMouseExited(evt);
            }
        });
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });
        panelCenter.add(btnDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 100, -1, -1));

        btnUtilisateur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnUser.png"))); // NOI18N
        btnUtilisateur.setBorderPainted(false);
        btnUtilisateur.setContentAreaFilled(false);
        btnUtilisateur.setFocusPainted(false);
        btnUtilisateur.setPreferredSize(new java.awt.Dimension(106, 102));
        btnUtilisateur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUtilisateurMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUtilisateurMouseExited(evt);
            }
        });
        btnUtilisateur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUtilisateurActionPerformed(evt);
            }
        });
        panelCenter.add(btnUtilisateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 200, -1, -1));

        btnApropos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnApropos.png"))); // NOI18N
        btnApropos.setBorderPainted(false);
        btnApropos.setContentAreaFilled(false);
        btnApropos.setFocusPainted(false);
        btnApropos.setPreferredSize(new java.awt.Dimension(106, 102));
        btnApropos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAproposMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAproposMouseExited(evt);
            }
        });
        btnApropos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAproposActionPerformed(evt);
            }
        });
        panelCenter.add(btnApropos, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 300, -1, -1));

        btnQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnQuitter.png"))); // NOI18N
        btnQuitter.setBorderPainted(false);
        btnQuitter.setContentAreaFilled(false);
        btnQuitter.setFocusPainted(false);
        btnQuitter.setPreferredSize(new java.awt.Dimension(106, 102));
        btnQuitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuitterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuitterMouseExited(evt);
            }
        });
        btnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitterActionPerformed(evt);
            }
        });
        panelCenter.add(btnQuitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 400, -1, -1));

        labVehicule.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labVehicule.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labVehicule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/labBG.png"))); // NOI18N
        labVehicule.setText("Véhicules");
        labVehicule.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelCenter.add(labVehicule, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 137, 80, -1));
        labVehicule.setVisible(false);

        labCategorie.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labCategorie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/labBG.png"))); // NOI18N
        labCategorie.setText("Catégories");
        labCategorie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelCenter.add(labCategorie, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 237, -1, -1));
        labCategorie.setVisible(false);

        labMarque.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labMarque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/labBG.png"))); // NOI18N
        labMarque.setText("Marques");
        labMarque.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelCenter.add(labMarque, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 337, -1, -1));
        labMarque.setVisible(false);

        labLieu.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/labBG.png"))); // NOI18N
        labLieu.setText("Lieux");
        labLieu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelCenter.add(labLieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 437, -1, -1));
        labLieu.setVisible(false);

        labDivision.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labDivision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/labBG2.png"))); // NOI18N
        labDivision.setText("Divisions");
        labDivision.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelCenter.add(labDivision, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 137, -1, -1));
        labDivision.setVisible(false);

        labUtilisateur.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labUtilisateur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/labBG2.png"))); // NOI18N
        labUtilisateur.setText("Utilisateur");
        labUtilisateur.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelCenter.add(labUtilisateur, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 237, -1, -1));
        labUtilisateur.setVisible(false);

        labApropos.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labApropos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/labBG2.png"))); // NOI18N
        labApropos.setText("A propos");
        labApropos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelCenter.add(labApropos, new org.netbeans.lib.awtextra.AbsoluteConstraints(706, 337, -1, -1));
        labApropos.setVisible(false);

        labQuitter.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        labQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/labBG2.png"))); // NOI18N
        labQuitter.setText("Quitter");
        labQuitter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        panelCenter.add(labQuitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 437, -1, -1));
        labQuitter.setVisible(false);

        labName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        labName.setForeground(new java.awt.Color(53, 83, 65));
        labName.setPreferredSize(new java.awt.Dimension(34, 20));
        panelCenter.add(labName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 25, 280, 33));

        labDate.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        labDate.setForeground(new java.awt.Color(53, 83, 65));
        labDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labDate.setPreferredSize(new java.awt.Dimension(220, 33));
        panelCenter.add(labDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 25, 210, -1));

        labelDate.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        labelDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        panelCenter.add(labelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 25, 200, 35));

        containerPanel.add(panelCenter, java.awt.BorderLayout.LINE_START);

        labBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg.png"))); // NOI18N
        containerPanel.add(labBG, java.awt.BorderLayout.LINE_END);

        getContentPane().add(containerPanel, java.awt.BorderLayout.LINE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVehiculeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculeMouseEntered
    btnVehicule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnVehicule2.png"))); // NOI18N
    labVehicule.setVisible(true);    }//GEN-LAST:event_btnVehiculeMouseEntered

    private void btnCategorieMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategorieMouseEntered
    btnCategorie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnCategorie2.png"))); // NOI18N
        labCategorie.setVisible(true);
    }//GEN-LAST:event_btnCategorieMouseEntered

    private void btnMarqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMarqueMouseEntered
btnMarque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnMarque2.png"))); // NOI18N
        labMarque.setVisible(true);        
    }//GEN-LAST:event_btnMarqueMouseEntered

    private void btnLieuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLieuMouseEntered
 btnLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnLieu2.png"))); // NOI18N
        labLieu.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnLieuMouseEntered

    private void btnDivisionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivisionMouseEntered
 btnDivision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnDivision2.png"))); // NOI18N
        labDivision.setVisible(true);     
    }//GEN-LAST:event_btnDivisionMouseEntered

    private void btnUtilisateurMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUtilisateurMouseEntered
btnUtilisateur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnUser2.png"))); // NOI18N
       labUtilisateur.setVisible(true);    }//GEN-LAST:event_btnUtilisateurMouseEntered

    private void btnAproposMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAproposMouseEntered
 btnApropos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnApropos2.png"))); // NOI18N
        labApropos.setVisible(true);       
    }//GEN-LAST:event_btnAproposMouseEntered

    private void btnQuitterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitterMouseEntered
btnQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnQuitter2.png"))); // NOI18N
        labQuitter.setVisible(true);      
    }//GEN-LAST:event_btnQuitterMouseEntered

    private void btnVehiculeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVehiculeMouseExited
btnVehicule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnVehicule.png"))); // NOI18N
        labVehicule.setVisible(false);        
    }//GEN-LAST:event_btnVehiculeMouseExited

    private void btnCategorieMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategorieMouseExited
btnCategorie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnCategorie.png"))); // NOI18N
        labCategorie.setVisible(false);       
    }//GEN-LAST:event_btnCategorieMouseExited

    private void btnMarqueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMarqueMouseExited
btnMarque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnMarque.png"))); // NOI18N
        labMarque.setVisible(false);       
    }//GEN-LAST:event_btnMarqueMouseExited

    private void btnLieuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLieuMouseExited
btnLieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnLieu.png"))); // NOI18N
        labLieu.setVisible(false);         
    }//GEN-LAST:event_btnLieuMouseExited

    private void btnDivisionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDivisionMouseExited
btnDivision.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnDivision.png"))); // NOI18N
        labDivision.setVisible(false);
    }//GEN-LAST:event_btnDivisionMouseExited

    private void btnUtilisateurMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUtilisateurMouseExited
btnUtilisateur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnUser.png"))); // NOI18N
        labUtilisateur.setVisible(false);        
    }//GEN-LAST:event_btnUtilisateurMouseExited

    private void btnAproposMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAproposMouseExited
 btnApropos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnApropos.png"))); // NOI18N
        labApropos.setVisible(false);       
    }//GEN-LAST:event_btnAproposMouseExited

    private void btnQuitterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitterMouseExited
 btnQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnQuitter.png"))); // NOI18N
        labQuitter.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitterMouseExited

    private void btnVehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculeActionPerformed
IHMVehicules ihmVehicules=new IHMVehicules();   
this.dispose();
ihmVehicules.setVisible(true);
    }//GEN-LAST:event_btnVehiculeActionPerformed

    private void btnCategorieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategorieActionPerformed
IHMCategorie ihmCategorie=new IHMCategorie();
this.dispose();
ihmCategorie.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnCategorieActionPerformed

    private void btnMarqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarqueActionPerformed
  IHMMarque ihmMarque=new IHMMarque();
this.dispose();
ihmMarque.setVisible(true);      // TODO add your handling code here:
    }//GEN-LAST:event_btnMarqueActionPerformed

    private void btnLieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLieuActionPerformed
   IHMLieu ihmLieu=new IHMLieu();
this.dispose();
ihmLieu.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_btnLieuActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
   IHMDivision ihmDivision=new IHMDivision();
this.dispose();
ihmDivision.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_btnDivisionActionPerformed

    private void btnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterActionPerformed
int i=JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment vous déconnecter ?", "Déconnexion...", 0); 
if(i==0)
{
    IHMLogin ihmLogin=new IHMLogin();
    this.dispose();
    ihmLogin.setVisible(true);
    }// TODO add your handling code here:
    }//GEN-LAST:event_btnQuitterActionPerformed

    private void btnAproposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAproposActionPerformed
JOptionPane.showMessageDialog(this, 
        "<html><body><h2>Application de Gestion Véhicules OCP</h2><br/>Auteur : <b> MOUSTAID Ayoub, </b> "
                + "élève ingénieur ENSET Mohammedia<br/>Date : <b>Juillet 2015</b><br/>"
                + "Contacte : <b>mstdayoub@gmail.com | 06 30 13 87 57</b></body></html>"
        , "A propos", 1);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAproposActionPerformed

    private void btnUtilisateurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtilisateurActionPerformed
     IHMUtilisateur ihmUtilisateur=new IHMUtilisateur();
     this.dispose();
     ihmUtilisateur.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnUtilisateurActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
Timer t=new Timer();
        t.schedule(new TimerTask() {
  public void run() {
      labelDate.setText(dateGetter.getTime());
  }
}, 0,1000);        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened
   
    


    /**
     * @param args the command line arguments
     */
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApropos;
    private javax.swing.JButton btnCategorie;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnLieu;
    private javax.swing.JButton btnMarque;
    private javax.swing.JButton btnQuitter;
    private javax.swing.JButton btnUtilisateur;
    private javax.swing.JButton btnVehicule;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JLabel labApropos;
    private javax.swing.JLabel labBG;
    private javax.swing.JLabel labCategorie;
    private javax.swing.JLabel labDate;
    private javax.swing.JLabel labDivision;
    private javax.swing.JLabel labLieu;
    private javax.swing.JLabel labMarque;
    private javax.swing.JLabel labName;
    private javax.swing.JLabel labQuitter;
    private javax.swing.JLabel labUtilisateur;
    private javax.swing.JLabel labVehicule;
    private javax.swing.JLabel labelDate;
    private javax.swing.JPanel panelCenter;
    // End of variables declaration//GEN-END:variables

}

