/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.SingletonConnexion;
import DAO.UtilisateurDAO;
import JavaBeans.Utilisateur;
import Utiles.DateGetter;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Moustaid
 */
public class IHMLogin extends javax.swing.JFrame {
private DateGetter dateGetter=new DateGetter();
private UtilisateurDAO uDAO=new UtilisateurDAO(SingletonConnexion.getInstance());
private String matricule;
private JButton[] btnS=new JButton[9];
public static Utilisateur user=new Utilisateur();
private int clicks=0;

    /**
     * Creates new form Accueil
     */
    public IHMLogin() {
        initComponents();
        setBtnS();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerPanel = new javax.swing.JPanel();
        panelCenter = new javax.swing.JPanel();
        labName = new javax.swing.JLabel();
        labDate = new javax.swing.JLabel();
        panelRecherche = new javax.swing.JPanel();
        labRechercherPar = new javax.swing.JLabel();
        panelBtn = new javax.swing.JPanel();
        btnQuitter = new javax.swing.JButton();
        panelTable = new javax.swing.JPanel();
        panelInfos = new javax.swing.JPanel();
        labPassword1 = new javax.swing.JLabel();
        txtMatricule = new javax.swing.JTextField();
        btnPassword = new javax.swing.JButton();
        labMatricule1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        panelShema = new javax.swing.JPanel();
        btnS0 = new javax.swing.JButton();
        btnS1 = new javax.swing.JButton();
        btnS2 = new javax.swing.JButton();
        btnS3 = new javax.swing.JButton();
        btnS4 = new javax.swing.JButton();
        btnS5 = new javax.swing.JButton();
        btnS6 = new javax.swing.JButton();
        btnS7 = new javax.swing.JButton();
        btnS8 = new javax.swing.JButton();
        btnShema = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        labBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Véhicules OCP - Authentification");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        containerPanel.setBackground(new java.awt.Color(255, 102, 102));
        containerPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        containerPanel.setLayout(new java.awt.BorderLayout());

        panelCenter.setBackground(new java.awt.Color(255, 255, 0));
        panelCenter.setOpaque(false);
        panelCenter.setPreferredSize(new java.awt.Dimension(800, 500));
        panelCenter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        labName.setForeground(new java.awt.Color(53, 83, 65));
        labName.setPreferredSize(new java.awt.Dimension(34, 20));
        panelCenter.add(labName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 25, 280, 33));

        labDate.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        labDate.setForeground(new java.awt.Color(53, 83, 65));
        labDate.setPreferredSize(new java.awt.Dimension(220, 33));
        panelCenter.add(labDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 25, -1, -1));

        panelRecherche.setOpaque(false);

        labRechercherPar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        labRechercherPar.setText("Authentification");
        panelRecherche.add(labRechercherPar);

        panelCenter.add(panelRecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 100, 560, 50));

        panelBtn.setOpaque(false);

        btnQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnQuitter.png"))); // NOI18N
        btnQuitter.setToolTipText("Retour");
        btnQuitter.setBorderPainted(false);
        btnQuitter.setContentAreaFilled(false);
        btnQuitter.setFocusPainted(false);
        btnQuitter.setPreferredSize(new java.awt.Dimension(106, 102));
        btnQuitter.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnQuitter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnQuitter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuitterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuitterMouseExited(evt);
            }
        });
        btnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitterActionPerformed(evt);
            }
        });
        panelBtn.add(btnQuitter);

        panelCenter.add(panelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 560, 100));

        panelTable.setOpaque(false);
        panelTable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInfos.setOpaque(false);
        panelInfos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labPassword1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labPassword1.setText("Mot de passe :");
        labPassword1.setPreferredSize(new java.awt.Dimension(130, 30));
        panelInfos.add(labPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 100, 30));

        txtMatricule.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtMatricule.setPreferredSize(new java.awt.Dimension(130, 30));
        panelInfos.add(txtMatricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 170, 30));

        btnPassword.setText("<html><center>Authentification<br/>(Mot de passe)</center><html>");
        btnPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasswordActionPerformed(evt);
            }
        });
        panelInfos.add(btnPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 110, 42));

        labMatricule1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labMatricule1.setText("Matricule :");
        labMatricule1.setPreferredSize(new java.awt.Dimension(130, 30));
        panelInfos.add(labMatricule1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 100, 30));

        txtPassword.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtPassword.setPreferredSize(new java.awt.Dimension(170, 30));
        panelInfos.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        panelTable.add(panelInfos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 270));

        panelShema.setPreferredSize(new java.awt.Dimension(320, 260));
        panelShema.setLayout(new java.awt.GridLayout(3, 3));

        btnS0.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        btnS0.setForeground(new java.awt.Color(153, 153, 153));
        btnS0.setText(".");
        btnS0.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnS0.setPreferredSize(new java.awt.Dimension(100, 100));
        btnS0.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnS0.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnS0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS0ActionPerformed(evt);
            }
        });
        panelShema.add(btnS0);

        btnS1.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        btnS1.setForeground(new java.awt.Color(153, 153, 153));
        btnS1.setText(".");
        btnS1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnS1.setPreferredSize(new java.awt.Dimension(100, 100));
        btnS1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnS1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS1ActionPerformed(evt);
            }
        });
        panelShema.add(btnS1);

        btnS2.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        btnS2.setForeground(new java.awt.Color(153, 153, 153));
        btnS2.setText(".");
        btnS2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnS2.setPreferredSize(new java.awt.Dimension(100, 100));
        btnS2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnS2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS2ActionPerformed(evt);
            }
        });
        panelShema.add(btnS2);

        btnS3.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        btnS3.setForeground(new java.awt.Color(153, 153, 153));
        btnS3.setText(".");
        btnS3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnS3.setPreferredSize(new java.awt.Dimension(100, 100));
        btnS3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnS3.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS3ActionPerformed(evt);
            }
        });
        panelShema.add(btnS3);

        btnS4.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        btnS4.setForeground(new java.awt.Color(153, 153, 153));
        btnS4.setText(".");
        btnS4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnS4.setPreferredSize(new java.awt.Dimension(100, 100));
        btnS4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnS4.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS4ActionPerformed(evt);
            }
        });
        panelShema.add(btnS4);

        btnS5.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        btnS5.setForeground(new java.awt.Color(153, 153, 153));
        btnS5.setText(".");
        btnS5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnS5.setPreferredSize(new java.awt.Dimension(100, 100));
        btnS5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnS5.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnS5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS5ActionPerformed(evt);
            }
        });
        panelShema.add(btnS5);

        btnS6.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        btnS6.setForeground(new java.awt.Color(153, 153, 153));
        btnS6.setText(".");
        btnS6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnS6.setPreferredSize(new java.awt.Dimension(100, 100));
        btnS6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnS6.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnS6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS6ActionPerformed(evt);
            }
        });
        panelShema.add(btnS6);

        btnS7.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        btnS7.setForeground(new java.awt.Color(153, 153, 153));
        btnS7.setText(".");
        btnS7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnS7.setPreferredSize(new java.awt.Dimension(100, 100));
        btnS7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnS7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnS7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS7ActionPerformed(evt);
            }
        });
        panelShema.add(btnS7);

        btnS8.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        btnS8.setForeground(new java.awt.Color(153, 153, 153));
        btnS8.setText(".");
        btnS8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnS8.setPreferredSize(new java.awt.Dimension(100, 100));
        btnS8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnS8.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        btnS8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS8ActionPerformed(evt);
            }
        });
        panelShema.add(btnS8);

        panelTable.add(panelShema, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 180, 150));

        btnShema.setText("<html><center>Authentification<br/>(Shéma)</center></html>");
        btnShema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShemaActionPerformed(evt);
            }
        });
        panelTable.add(btnShema, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 110, 42));

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        panelTable.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        panelCenter.add(panelTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 192, 670, 270));

        containerPanel.add(panelCenter, java.awt.BorderLayout.LINE_START);

        labBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg2.png"))); // NOI18N
        containerPanel.add(labBG, java.awt.BorderLayout.LINE_END);

        getContentPane().add(containerPanel, java.awt.BorderLayout.LINE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitterMouseEntered
        btnQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnQuitter2.png"))); // NOI18N
    }//GEN-LAST:event_btnQuitterMouseEntered

    private void btnQuitterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuitterMouseExited
        btnQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnQuitter.png"))); // NOI18N
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitterMouseExited

    private void btnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitterActionPerformed
int i=JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment quitter l'application ?", "Quitter...", 0); 
if(i==0)
System.exit(0);       // TODO add your handling code here:
    }//GEN-LAST:event_btnQuitterActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
labDate.setText(dateGetter.getDayName()+", "+dateGetter.getDateNow());

// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    public void setBtnS() {
        btnS[0]=btnS0;
        btnS[1]=btnS1;
        btnS[2]=btnS2;
        btnS[3]=btnS3;
        btnS[4]=btnS4;
        btnS[5]=btnS5;
        btnS[6]=btnS6;
        btnS[7]=btnS7;
        btnS[8]=btnS8;
    }

    private void btnPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasswordActionPerformed
       
                String matricule=txtMatricule.getText();
        user=uDAO.read(matricule);
        String password="";
        if(txtPassword.getPassword().length>0)
        {
        for(int i=0;i<txtPassword.getPassword().length;i++)
            password=password+txtPassword.getPassword()[i];
        }
        if(matricule.equals(user.getMatriculeUser())&&password.equals(user.getPassword()))
{
IHMAccueil ihmAccueil=new IHMAccueil();    
this.dispose();
ihmAccueil.setVisible(true);
}
        else {
            JOptionPane.showMessageDialog(this, "Authentification refusée : Données incorrectes");
        txtPassword.setText("");
        }
    }//GEN-LAST:event_btnPasswordActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        for(int i=0;i<btnS.length;i++)
{
btnS[i].setEnabled(true);
}
clicks=0;// TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnShemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShemaActionPerformed
String shema="";
        for(int i=0;i<btnS.length;i++)
{
if(!btnS[i].isEnabled())
    shema=shema+"S"+i;
}
 user=uDAO.read();
        String password="";
        if(shema.equals(user.getShema()))
{
IHMAccueil ihmAccueil=new IHMAccueil();    
this.dispose();
ihmAccueil.setVisible(true);
}
        else {
            JOptionPane.showMessageDialog(this, "Authentification refusée : Shéma incorrecte");
            for(int i=0;i<btnS.length;i++)
        btnS[i].setEnabled(true);
            clicks=0;
        }
    // TODO add your handling code here:
    }//GEN-LAST:event_btnShemaActionPerformed

    private void btnS0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS0ActionPerformed
if(clicks<4)
{
        btnS0.setEnabled(false);
clicks++;
}
    }//GEN-LAST:event_btnS0ActionPerformed

    private void btnS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS1ActionPerformed
if(clicks<4)
{
        btnS1.setEnabled(false);
clicks++;
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnS1ActionPerformed

    private void btnS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS2ActionPerformed
if(clicks<4)
{
        btnS2.setEnabled(false);
clicks++;
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnS2ActionPerformed

    private void btnS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS3ActionPerformed
if(clicks<4)
{
        btnS3.setEnabled(false);
clicks++;
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnS3ActionPerformed

    private void btnS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS4ActionPerformed
if(clicks<4)
{
        btnS4.setEnabled(false);
clicks++;
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnS4ActionPerformed

    private void btnS5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS5ActionPerformed
if(clicks<4)
{
        btnS5.setEnabled(false);
clicks++;
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnS5ActionPerformed

    private void btnS6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS6ActionPerformed
if(clicks<4)
{
        btnS6.setEnabled(false);
clicks++;
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnS6ActionPerformed

    private void btnS7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS7ActionPerformed
if(clicks<4)
{
        btnS7.setEnabled(false);
clicks++;
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnS7ActionPerformed

    private void btnS8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS8ActionPerformed
if(clicks<4)
{
        btnS8.setEnabled(false);
clicks++;
}        // TODO add your handling code here:
    }//GEN-LAST:event_btnS8ActionPerformed


     
       


    /**
     * @param args the command line arguments
     */
 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHMAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHMAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHMAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHMAccueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new IHMLogin().setVisible(true);
            }
        });
 }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPassword;
    private javax.swing.JButton btnQuitter;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnS0;
    private javax.swing.JButton btnS1;
    private javax.swing.JButton btnS2;
    private javax.swing.JButton btnS3;
    private javax.swing.JButton btnS4;
    private javax.swing.JButton btnS5;
    private javax.swing.JButton btnS6;
    private javax.swing.JButton btnS7;
    private javax.swing.JButton btnS8;
    private javax.swing.JButton btnShema;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JLabel labBG;
    private javax.swing.JLabel labDate;
    private javax.swing.JLabel labMatricule1;
    private javax.swing.JLabel labName;
    private javax.swing.JLabel labPassword1;
    private javax.swing.JLabel labRechercherPar;
    private javax.swing.JPanel panelBtn;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelInfos;
    private javax.swing.JPanel panelRecherche;
    private javax.swing.JPanel panelShema;
    private javax.swing.JPanel panelTable;
    private javax.swing.JTextField txtMatricule;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

   
}
