/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DAO.SingletonConnexion;
import DAO.UtilisateurDAO;
import JavaBeans.Utilisateur;
import Utiles.DateGetter;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author Moustaid
 */
public class IHMUtilisateur extends javax.swing.JFrame {
private DateGetter dateGetter=new DateGetter();
private UtilisateurDAO uDAO=new UtilisateurDAO(SingletonConnexion.getInstance());
private String matricule,newPassword="",newShema="";
private JButton[] btnS=new JButton[9];
private int clicks=0;

    /**
     * Creates new form Accueil
     */
    public IHMUtilisateur() {
        initComponents();
        setBtnS();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerPanel = new javax.swing.JPanel();
        panelCenter = new javax.swing.JPanel();
        labName = new javax.swing.JLabel();
        labDate = new javax.swing.JLabel();
        panelRecherche = new javax.swing.JPanel();
        labRechercherPar = new javax.swing.JLabel();
        panelBtn = new javax.swing.JPanel();
        btnModifier = new javax.swing.JButton();
        btnAccueil = new javax.swing.JButton();
        panelTable = new javax.swing.JPanel();
        panelInfos = new javax.swing.JPanel();
        btnPassword = new javax.swing.JButton();
        labPassword1 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        labPrenom = new javax.swing.JLabel();
        txtPrenom = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        labNom = new javax.swing.JLabel();
        txtMatricule = new javax.swing.JTextField();
        labMatricule1 = new javax.swing.JLabel();
        panelShema = new javax.swing.JPanel();
        btnS0 = new javax.swing.JButton();
        btnS1 = new javax.swing.JButton();
        btnS2 = new javax.swing.JButton();
        btnS3 = new javax.swing.JButton();
        btnS4 = new javax.swing.JButton();
        btnS5 = new javax.swing.JButton();
        btnS6 = new javax.swing.JButton();
        btnS7 = new javax.swing.JButton();
        btnS8 = new javax.swing.JButton();
        btnShema = new javax.swing.JButton();
        labShema = new javax.swing.JLabel();
        labBG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Véhicules OCP - Utilisateur");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        containerPanel.setBackground(new java.awt.Color(255, 102, 102));
        containerPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        containerPanel.setLayout(new java.awt.BorderLayout());

        panelCenter.setBackground(new java.awt.Color(255, 255, 0));
        panelCenter.setOpaque(false);
        panelCenter.setPreferredSize(new java.awt.Dimension(800, 500));
        panelCenter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labName.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        labName.setForeground(new java.awt.Color(53, 83, 65));
        labName.setPreferredSize(new java.awt.Dimension(34, 20));
        panelCenter.add(labName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 25, 280, 33));

        labDate.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        labDate.setForeground(new java.awt.Color(53, 83, 65));
        labDate.setPreferredSize(new java.awt.Dimension(220, 33));
        panelCenter.add(labDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 25, -1, -1));

        panelRecherche.setOpaque(false);

        labRechercherPar.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        labRechercherPar.setText("Utilisateur");
        panelRecherche.add(labRechercherPar);

        panelCenter.add(panelRecherche, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 100, 560, 50));

        panelBtn.setOpaque(false);

        btnModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnUpdate.png"))); // NOI18N
        btnModifier.setToolTipText("Appliquer Modifications");
        btnModifier.setBorderPainted(false);
        btnModifier.setContentAreaFilled(false);
        btnModifier.setFocusPainted(false);
        btnModifier.setPreferredSize(new java.awt.Dimension(106, 102));
        btnModifier.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnModifier.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnModifier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnModifierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnModifierMouseExited(evt);
            }
        });
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });
        panelBtn.add(btnModifier);

        btnAccueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnAccueil.png"))); // NOI18N
        btnAccueil.setToolTipText("Retour");
        btnAccueil.setBorderPainted(false);
        btnAccueil.setContentAreaFilled(false);
        btnAccueil.setFocusPainted(false);
        btnAccueil.setPreferredSize(new java.awt.Dimension(106, 102));
        btnAccueil.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnAccueil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAccueil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAccueilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAccueilMouseExited(evt);
            }
        });
        btnAccueil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccueilActionPerformed(evt);
            }
        });
        panelBtn.add(btnAccueil);

        panelCenter.add(panelBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 560, 100));

        panelTable.setOpaque(false);
        panelTable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelInfos.setOpaque(false);
        panelInfos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnPassword.setText("Changer Mot de passe");
        btnPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasswordActionPerformed(evt);
            }
        });
        panelInfos.add(btnPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 170, 30));

        labPassword1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labPassword1.setText("Mot de passe :");
        labPassword1.setPreferredSize(new java.awt.Dimension(130, 30));
        panelInfos.add(labPassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 100, 30));

        txtPassword.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtPassword.setEnabled(false);
        txtPassword.setPreferredSize(new java.awt.Dimension(130, 30));
        panelInfos.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 170, 30));

        labPrenom.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labPrenom.setText("Prénom :");
        labPrenom.setPreferredSize(new java.awt.Dimension(130, 30));
        panelInfos.add(labPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 100, 30));

        txtPrenom.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtPrenom.setPreferredSize(new java.awt.Dimension(130, 30));
        panelInfos.add(txtPrenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 170, 30));

        txtNom.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtNom.setPreferredSize(new java.awt.Dimension(130, 30));
        panelInfos.add(txtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 170, 30));

        labNom.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labNom.setText("Nom :");
        labNom.setPreferredSize(new java.awt.Dimension(130, 30));
        panelInfos.add(labNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 100, 30));

        txtMatricule.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtMatricule.setPreferredSize(new java.awt.Dimension(130, 30));
        panelInfos.add(txtMatricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 170, 30));

        labMatricule1.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labMatricule1.setText("Matricule :");
        labMatricule1.setPreferredSize(new java.awt.Dimension(130, 30));
        panelInfos.add(labMatricule1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 100, 30));

        panelTable.add(panelInfos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 270));

        panelShema.setPreferredSize(new java.awt.Dimension(320, 260));
        panelShema.setLayout(new java.awt.GridLayout(3, 3));

        btnS0.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        btnS0.setForeground(new java.awt.Color(153, 153, 153));
        btnS0.setText(".");
        btnS0.setPreferredSize(new java.awt.Dimension(100, 100));
        btnS0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS0ActionPerformed(evt);
            }
        });
        panelShema.add(btnS0);

        btnS1.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        btnS1.setForeground(new java.awt.Color(153, 153, 153));
        btnS1.setText(".");
        btnS1.setPreferredSize(new java.awt.Dimension(100, 100));
        btnS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS1ActionPerformed(evt);
            }
        });
        panelShema.add(btnS1);

        btnS2.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        btnS2.setForeground(new java.awt.Color(153, 153, 153));
        btnS2.setText(".");
        btnS2.setPreferredSize(new java.awt.Dimension(100, 100));
        btnS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS2ActionPerformed(evt);
            }
        });
        panelShema.add(btnS2);

        btnS3.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        btnS3.setForeground(new java.awt.Color(153, 153, 153));
        btnS3.setText(".");
        btnS3.setPreferredSize(new java.awt.Dimension(100, 100));
        btnS3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS3ActionPerformed(evt);
            }
        });
        panelShema.add(btnS3);

        btnS4.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        btnS4.setForeground(new java.awt.Color(153, 153, 153));
        btnS4.setText(".");
        btnS4.setPreferredSize(new java.awt.Dimension(100, 100));
        btnS4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS4ActionPerformed(evt);
            }
        });
        panelShema.add(btnS4);

        btnS5.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        btnS5.setForeground(new java.awt.Color(153, 153, 153));
        btnS5.setText(".");
        btnS5.setPreferredSize(new java.awt.Dimension(100, 100));
        btnS5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS5ActionPerformed(evt);
            }
        });
        panelShema.add(btnS5);

        btnS6.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        btnS6.setForeground(new java.awt.Color(153, 153, 153));
        btnS6.setText(".");
        btnS6.setPreferredSize(new java.awt.Dimension(100, 100));
        btnS6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS6ActionPerformed(evt);
            }
        });
        panelShema.add(btnS6);

        btnS7.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        btnS7.setForeground(new java.awt.Color(153, 153, 153));
        btnS7.setText(".");
        btnS7.setPreferredSize(new java.awt.Dimension(100, 100));
        btnS7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS7ActionPerformed(evt);
            }
        });
        panelShema.add(btnS7);

        btnS8.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        btnS8.setForeground(new java.awt.Color(153, 153, 153));
        btnS8.setText(".");
        btnS8.setPreferredSize(new java.awt.Dimension(100, 100));
        btnS8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS8ActionPerformed(evt);
            }
        });
        panelShema.add(btnS8);

        panelTable.add(panelShema, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, 180, 150));

        btnShema.setText("Changer Shéma");
        btnShema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShemaActionPerformed(evt);
            }
        });
        panelTable.add(btnShema, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 150, 30));

        labShema.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        labShema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labShema.setText("Shéma d'authentification ");
        labShema.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labShema.setPreferredSize(new java.awt.Dimension(130, 30));
        panelTable.add(labShema, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 180, -1));

        panelCenter.add(panelTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 192, 670, 270));

        containerPanel.add(panelCenter, java.awt.BorderLayout.LINE_START);

        labBG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg2.png"))); // NOI18N
        containerPanel.add(labBG, java.awt.BorderLayout.LINE_END);

        getContentPane().add(containerPanel, java.awt.BorderLayout.LINE_END);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccueilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccueilMouseEntered
        btnAccueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnAccueil2.png"))); // NOI18N
    }//GEN-LAST:event_btnAccueilMouseEntered

    private void btnAccueilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAccueilMouseExited
        btnAccueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnAccueil.png"))); // NOI18N
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAccueilMouseExited

    private void btnAccueilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccueilActionPerformed
IHMAccueil ihmAccueil=new IHMAccueil();   
this.dispose();
ihmAccueil.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btnAccueilActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        labDate.setText(dateGetter.getDayName()+", "+dateGetter.getDateNow());
        labName.setText(IHMLogin.user.getNomUser().toUpperCase()+" "+IHMLogin.user.getPrenomUser());
UtilisateurDAO uDAO=new UtilisateurDAO(SingletonConnexion.getInstance());
Utilisateur u=new Utilisateur();
u=uDAO.read(IHMLogin.user.getMatriculeUser());
txtMatricule.setText(IHMLogin.user.getMatriculeUser());
txtNom.setText(u.getNomUser());
txtPrenom.setText(u.getPrenomUser());
txtPassword.setText(u.getPassword());
String shema=u.getShema();

for(int i=0;i<btnS.length;i++)
{
if(shema.contains("S"+i))
    btnS[i].setEnabled(false);
clicks++;
}


// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    public void setBtnS() {
        btnS[0]=btnS0;
        btnS[1]=btnS1;
        btnS[2]=btnS2;
        btnS[3]=btnS3;
        btnS[4]=btnS4;
        btnS[5]=btnS5;
        btnS[6]=btnS6;
        btnS[7]=btnS7;
        btnS[8]=btnS8;
    }

    private void btnModifierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifierMouseEntered
        btnModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnUpdate2.png"))); // NOI18N
    }//GEN-LAST:event_btnModifierMouseEntered

    private void btnModifierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModifierMouseExited
        btnModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnUpdate.png"))); // NOI18N
    }//GEN-LAST:event_btnModifierMouseExited

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
newShema="";
        for(int i=0;i<btnS.length;i++)
{
if(!btnS[i].isEnabled())
    newShema=newShema+"S"+i;
}
System.out.print(newShema);
        if(txtMatricule.getText().length()>0 && txtPassword.getText().length()>0)
{
    if(newShema.length()!=8)
        JOptionPane.showMessageDialog(this, "Shéma incorrect (4choix)");
    else{
Utilisateur u=new Utilisateur();
u.setMatriculeUser(txtMatricule.getText());
u.setNomUser(txtNom.getText());
u.setPrenomUser(txtPrenom.getText());
u.setPassword(txtPassword.getText());
u.setShema(newShema);
uDAO.update(u);
IHMLogin.user=u;
JOptionPane.showMessageDialog(this, "Modification effectuée");
    }
}
else
{
JOptionPane.showMessageDialog(this, "Champs Matricule et Mot de passe ne doivent pas etre vides ! ");
}
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasswordActionPerformed
String pwd=JOptionPane.showInputDialog(this, "Nouveau Mot de passe :") ;    
if(pwd!=null)
{
    newPassword=pwd;
    txtPassword.setText(newPassword);
}
    }//GEN-LAST:event_btnPasswordActionPerformed

    private void btnShemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShemaActionPerformed
   for(int i=0;i<btnS.length;i++)
        btnS[i].setEnabled(true);
            clicks=0;
            }//GEN-LAST:event_btnShemaActionPerformed

    private void btnS0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS0ActionPerformed
if(clicks<4)
{
        btnS0.setEnabled(false);
clicks++;
}          // TODO add your handling code here:
    }//GEN-LAST:event_btnS0ActionPerformed

    private void btnS1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS1ActionPerformed
if(clicks<4)
{
        btnS1.setEnabled(false);
clicks++;
}          // TODO add your handling code here:
    }//GEN-LAST:event_btnS1ActionPerformed

    private void btnS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS2ActionPerformed
if(clicks<4)
{
        btnS2.setEnabled(false);
clicks++;
}          // TODO add your handling code here:
    }//GEN-LAST:event_btnS2ActionPerformed

    private void btnS3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS3ActionPerformed
if(clicks<4)
{
        btnS3.setEnabled(false);
clicks++;
}          // TODO add your handling code here:
    }//GEN-LAST:event_btnS3ActionPerformed

    private void btnS4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS4ActionPerformed
if(clicks<4)
{
        btnS4.setEnabled(false);
clicks++;
}          // TODO add your handling code here:
    }//GEN-LAST:event_btnS4ActionPerformed

    private void btnS5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS5ActionPerformed
if(clicks<4)
{
        btnS5.setEnabled(false);
clicks++;
}          // TODO add your handling code here:
    }//GEN-LAST:event_btnS5ActionPerformed

    private void btnS6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS6ActionPerformed
if(clicks<4)
{
        btnS6.setEnabled(false);
clicks++;
}          // TODO add your handling code here:
    }//GEN-LAST:event_btnS6ActionPerformed

    private void btnS7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS7ActionPerformed
if(clicks<4)
{
        btnS7.setEnabled(false);
clicks++;
}          // TODO add your handling code here:
    }//GEN-LAST:event_btnS7ActionPerformed

    private void btnS8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS8ActionPerformed
if(clicks<4)
{
        btnS8.setEnabled(false);
clicks++;
}          // TODO add your handling code here:
    }//GEN-LAST:event_btnS8ActionPerformed


     
       


    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccueil;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnPassword;
    private javax.swing.JButton btnS0;
    private javax.swing.JButton btnS1;
    private javax.swing.JButton btnS2;
    private javax.swing.JButton btnS3;
    private javax.swing.JButton btnS4;
    private javax.swing.JButton btnS5;
    private javax.swing.JButton btnS6;
    private javax.swing.JButton btnS7;
    private javax.swing.JButton btnS8;
    private javax.swing.JButton btnShema;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JLabel labBG;
    private javax.swing.JLabel labDate;
    private javax.swing.JLabel labMatricule1;
    private javax.swing.JLabel labName;
    private javax.swing.JLabel labNom;
    private javax.swing.JLabel labPassword1;
    private javax.swing.JLabel labPrenom;
    private javax.swing.JLabel labRechercherPar;
    private javax.swing.JLabel labShema;
    private javax.swing.JPanel panelBtn;
    private javax.swing.JPanel panelCenter;
    private javax.swing.JPanel panelInfos;
    private javax.swing.JPanel panelRecherche;
    private javax.swing.JPanel panelShema;
    private javax.swing.JPanel panelTable;
    private javax.swing.JTextField txtMatricule;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPrenom;
    // End of variables declaration//GEN-END:variables

   
}
